'use strict';

let validDate = new Date();
validDate.setDate(validDate.getDate() + 7);

module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */

     await queryInterface.bulkInsert('Items', [
      {
        title: 'Хлеб',
        description: 'Подарю свежий хлеб. Испек сам',
        img: '/img/food_10.jpg',
        category_id: 1,
        user_id: 1,
        city: 'Москва',
        address: 'ул. Вавилова, 1',
        available: true,
        coordinatesX: 55.761469,
        coordinatesY: 37.655561,
        validUntil: validDate,
        createdAt: new Date(),
        updatedAt: new Date(),
     },
     {
      title: 'Свитер',
      description: 'Новый свитер. Куплен в Zara. Отдаю, потому что оказался мал. Размер M.',
      img: '/img/cloth_5.jpg',
      category_id: 2,
      user_id: 1,
      city: 'Москва',
      address: 'ул. Вавилова, 2',
      available: true,
      coordinatesX: 55.741469,
      coordinatesY: 37.615561,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Царский стул',
      description: 'Подарю стул для людей, которые знают себе цену',
      img: '/img/fur_7.jpg',
      category_id: 3,
      user_id: 1,
      city: 'Москва',
      address: 'ул. Вавилова, 3',
      available: true,
      coordinatesX: 55.751469,
      coordinatesY: 37.625561,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Кабачок',
      description: 'Отдам кабачок',
      img: '/img/food_17.jpg',
      category_id: 1,
      user_id: 1,
      city: 'Москва',
      address: 'ул. Вавилова, 4',
      available: true,
      coordinatesX: 55.741479,
      coordinatesY: 37.645561,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Морковка',
      description: 'Отдам морковку с собственного огорода. Вкусная, сочная.',
      img: '/img/food_8.jpg',
      category_id: 1,
      user_id: 1,
      city: 'Москва',
      address: 'ул. Вавилова, 5',
      available: true,
      coordinatesX: 55.745469,
      coordinatesY: 37.615591,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Носки',
      description: 'Подарю детские носки трех цветов - серые, фиолетовые и желтые',
      img: '/img/cloth_2.jpg',
      category_id: 2,
      user_id: 2,
      city: 'Москва',
      address: 'ул. Вавилова, 6',
      available: true,
      coordinatesX: 55.641469,
      coordinatesY: 37.715561,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Болты от шкафа Икеа',
      description: 'После сборки шкафа осталось много ненужных деталей. Подарю безвозмездно.',
      img: '/img/fur_5.jpg',
      category_id: 3,
      user_id: 1,
      city: 'Москва',
      address: 'ул. Вавилова, 7',
      available: true,
      coordinatesX: 55.941469,
      coordinatesY: 37.6145561,
      validUntil: validDate,
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      title: 'Много одежды',
      description: 'Подарю хорошему человеку весь свой гардероб.',
      img: '/img/cloth_1.jpg',
      category_id: 3,
      user_id: 2,
      city: 'Москва',
      address: 'ул. Вавилова, 8',
      available: true,
      coordinatesX: 55.7414769,
      coordinatesY: 37.61561,
      validUntil: validDate,
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
    title: 'Много футболок зеленого цвета',
    description: 'Отдам 5 футболок зеленого цвета. Состояние хорошее.',
    img: '/img/cloth_3.jpg',
    category_id: 2,
    user_id: 3,
    city: 'Москва',
    address: 'ул. Вавилова, 9',
    available: true,
    coordinatesX: 55.7414469,
    coordinatesY: 37.615461,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Женские шорты',
    description: 'Подарю женские шорты. Состояние отличное.',
    img: '/img/cloth_4.jpg',
    category_id: 2,
    user_id: 2,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.7414369,
    coordinatesY: 37.6152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Хлеб из собственной пекарни',
    description: 'Могу поделиться 10 батонами белого хлеба в день. Каждое день с 9 утра.',
    img: '/img/food_11.jpg',
    category_id: 1,
    user_id: 3,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.7414369,
    coordinatesY: 37.6152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Хлеб ручной работы',
    description: 'Могу поделиться 5 батонами белого хлеба в день. Пишите в личку в Вотсап',
    img: '/img/food_9.jpg',
    category_id: 1,
    user_id: 3,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.7254369,
    coordinatesY: 37.6152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Мангал',
    description: 'Отдаю безвозмедно свой дачный мангал. Почти новый.',
    img: '/img/fur_1.jpg',
    category_id: 3,
    user_id: 3,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.7254369,
    coordinatesY: 37.64152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Стеллаж',
    description: 'Подарю стеллаж. Икеа. По вопросам пишите в WhatsApp',
    img: '/img/fur_6.jpg',
    category_id: 3,
    user_id: 2,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.78254369,
    coordinatesY: 37.64152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Дачная черешня',
    description: 'Могу поделиться дачной. Слишком большой урожай. До сих пор не можем съесть:)',
    img: '/img/food_4.jpg',
    category_id: 1,
    user_id: 1,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.78254369,
    coordinatesY: 37.64152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Пицца',
    description: 'Люблю готовить пиццу. По пятницам готова дарить одну хорошему человеку. Пишите в Telegram',
    img: '/img/food_1.jpg',
    category_id: 1,
    user_id: 2,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.78254369,
    coordinatesY: 37.64152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Сининй диван',
    description: 'Отдам синий диван. Состояние удовлетворительное.',
    img: '/img/fur_2.jpg',
    category_id: 1,
    user_id: 2,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.78254369,
    coordinatesY: 37.674152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Кровать',
    description: 'Отдам свою кровать нуждающимся. По причине покупки новой. Пишите в Viber',
    img: '/img/fur_4.jpg',
    category_id: 1,
    user_id: 1,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.80254369,
    coordinatesY: 37.674152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Ящик персиков',
    description: 'Подарю ящик персиков. Прислал дядя из Сочи. Пишите в Telegram',
    img: '/img/food_13.jpg',
    category_id: 1,
    user_id: 1,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.80254369,
    coordinatesY: 37.704152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Фермерские яйца',
    description: 'Отдам яйца с собственной фермы. Пишите в Telegram',
    img: '/img/food_5.jpg',
    category_id: 1,
    user_id: 3,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.80254369,
    coordinatesY: 37.704152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   {
    title: 'Огурцы и петрушка',
    description: 'Поделюсь дачными овощами. Пишите в Telegram',
    img: '/img/food_7.jpg',
    category_id: 1,
    user_id: 1,
    city: 'Москва',
    address: 'ул. Вавилова, 10',
    available: true,
    coordinatesX: 55.80254369,
    coordinatesY: 37.694152561,
    validUntil: validDate,
     createdAt: new Date(),
     updatedAt: new Date(),
   },
   ], {});

  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
     await queryInterface.bulkDelete('Items', null, {});
  }
};
